---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-monitoring-server
  labels:
    app: edge-monitoring-server
spec:
  selector:
    matchLabels:
      app: edge-monitoring-server
  replicas: {{ .Values.config.replicas }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: edge-monitoring-server
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
      - name: server
        image: "{{ .Values.images.tags.server }}"
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        command: ["python", "edge_monitoring_server.py"]
        livenessProbe:
          httpGet:
            path: /edges/healthz
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
