---
apiVersion: v1
kind: Service
metadata:
  name: edge-monitoring-server
spec:
  selector:
    app: edge-monitoring-server
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: server
